name: Git Opts
description: Configure git options for git clone/git fetch
author: https://github.com/jasonwbarnett
requirements: []
configuration:
  properties:
    depth:
      type: string
    filter:
      type: string
    sparse-checkout:
      type: boolean
    sparse-checkout-paths:
      type: array
  required: []
  additionalProperties: false
