#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_DEPTH:-}" != "" ]]; then
  echo "--- :git: Configuring depth"
  export BUILDKITE_GIT_CLONE_DEPTH="${BUILDKITE_PLUGIN_GIT_OPTS_DEPTH}"
  export BUILDKITE_GIT_FETCH_FLAGS="${BUILDKITE_GIT_FETCH_FLAGS} --depth=${BUILDKITE_PLUGIN_GIT_OPTS_DEPTH}"
fi

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_FILTER:-}" != "" ]]; then
  echo "--- :git: Configuring filter"
  export BUILDKITE_GIT_CLONE_FILTER="${BUILDKITE_PLUGIN_GIT_OPTS_FILTER}"
fi

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_SPARSE_CHECKOUT:-}" == "true" ]]; then
  echo "--- :git: Configuring sparse checkout"
  export BUILDKITE_GIT_SPARSE_CHECKOUT="true"
fi

if plugin_read_list_into_result "SPARSE_CHECKOUT_PATHS"; then
  echo "--- :git: Configuring sparse checkout paths"
  # Join array elements with commas
  OLD_IFS="$IFS"
  IFS=','
  BUILDKITE_GIT_SPARSE_CHECKOUT_PATHS="${result[*]}"
  IFS="$OLD_IFS"
  export BUILDKITE_GIT_SPARSE_CHECKOUT_PATHS
fi
