#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_DEPTH:-}" != "" ]]; then
  echo "--- :git: Configuring depth"
  export BUILDKITE_GIT_CLONE_DEPTH="${BUILDKITE_PLUGIN_GIT_OPTS_DEPTH}"
fi

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_FILTER:-}" != "" ]]; then
  echo "--- :git: Configuring filter"
  export BUILDKITE_GIT_CLONE_FILTER="${BUILDKITE_PLUGIN_GIT_OPTS_FILTER}"
fi

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_SPARSE_CHECKOUT:-}" == "true" ]]; then
  echo "--- :git: Configuring sparse checkout"
  export BUILDKITE_GIT_SPARSE_CHECKOUT="true"
fi

if [[ "${BUILDKITE_PLUGIN_GIT_OPTS_SPARSE_CHECKOUT_PATHS:-}" != "" ]]; then
  echo "--- :git: Configuring sparse checkout paths"
  export BUILDKITE_GIT_SPARSE_CHECKOUT_PATHS="${BUILDKITE_PLUGIN_GIT_OPTS_SPARSE_CHECKOUT_PATHS}"
fi
